server:
  port: 8090

spring:
 
  datasource:
    url: jdbc:mysql://localhost:3306/bank?useSSL=false
    username: root
    password: pass@word1
  jpa:
    hibernate:
     
      ddl-auto: update
    show-sql: true
   
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
   

logging:
  level:
    org:
      springframework:
        web: ERROR
    com: DEBUG